server:
  port: 8001

  # 服务名
spring:
  application:
    name: service-edu

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli
    username: root
    password: 12345678

  # 时间格式和时区配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# mybatis日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#aliyun:
#  oss:
#    file:
#      endpoint: oss-cn-guangzhou.aliyuncs.com
#      accessKeyId: LTAI5t6oV8zBYuRfccajo2Nj
#      accessKeySecret: Aq1ZKNMkGW9Ul9C5kLRxpBEA2e3xIH
#      bucketname: edu-10-test

ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 10000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 2000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000 #断路器超时时间，默认1000ms